namespaces:
  - id: m4rc3l
    name: M4rc3l
    url: https://status.m4rc3l.de

services:
  - id: google
    name: Google
    namespace: m4rc3l
    url: https://www.google.com/
    method: HEAD
    timeout: 5
    status: 200

  - id: abc
    name: ABC
    namespace: m4rc3l
    url: https://abc.m4rc3l.de/abc
    method: HEAD
    timeout: 5
    status: 200
